FRONTENDBOOTCAMP-13th/HS-fish-shop

src/components/gnb-main/gnb-main.css
=> 🐛 fix: 모바일 하단버튼 z-index 수정

index.html, src/pages/drama-page/drama-page.html, src/pages/main-page/main-page.html, src/pages/movie-page/movie-page.html
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
각 card list있는 공간에 버튼을 추가했고 index페이지에서 중복된요소와 컴포넌트와 페이지를 확인할수있게 추가 텍스트로 구분함
resolves #25
=> Featcard list button add

src/pages/login-page/login-page.css
- [] 새로운 기능 추가
- [0] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves 29#
=> fix:loginpage checkout icon path edit

src/pages/main-page/main-page.html
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
버튼 제거
resolves #32
=> 🐛 fix : button이 하나더 생성됨

src/pages/findId-page/findId-page.css, src/pages/findPw-page/findPw-page.css, src/pages/login-page/login-page.css, src/pages/signup-page/signup-page.css
- [] 새로운 기능 추가
- [0] 버그 수정
- [0] CSS 등 사용자 UI 디자인 변경
- [] 코드 리팩토링
- [] 문서 수정
icon path and size fix
resolves #33
=> 🐛fix:loginpage checkout icon path edit and size

src/pages/drama-page/drama-page.html, src/pages/main-page/main-page.html, src/pages/movie-page/movie-page.html
=> 🎨 feat: 링크 연결

index.html
- [0] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- [] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
index-link수정 및 배치
resolves #39
=> 🎨feat:index-link-delete

index.html, intro.html, src/styles/index.css
- [0] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- [] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
resolves#43
=> 🎨feat: Add intro and modify layout of index.html

src/pages/drama-page/drama-page.html, src/pages/findId-page/findId-page.html, src/pages/findPw-page/findPw-page.html, src/pages/login-page/login-page.html, src/pages/main-page/main-page.html, src/pages/movie-page/movie-page.html, src/pages/signup-page/signup-page.html
- [0] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
1. main,movie,drama page에 profile page 연결
2. main,movie,drama page 모바일 하단 바에 기록, 검색 버튼 각각 my-history, mobile-search연결
3. login,findId,findPw,signup 전부 서로 연결후 landing, main page랑 연결
resolves #46
=> 🎨feat: all connected pages

src/pages/drama-page/drama-page.html, src/pages/main-page/main-page.html, src/pages/movie-page/movie-page.html
main-visual에 텍스트 추가와 공지사항 테스트를 삭제했습니다
resolves #51
=> ♻️ refactor:  불필요한 텍스트 삭제 및 메인 비쥬올 이미지 추가 텍스트 작성

src/styles/index.css
- [0] 새로운 기능 추가
- [] 버그 수정
- [0] CSS 등 사용자 UI 디자인 변경
- [] 코드 리팩토링
- [] 문서 수정
그리드 재배치 및 그에 따른 css수정
resolves #54
=> 🎨feat:nav_grid renewal

index.html, src/styles/index.css
- [] 새로운 기능 추가
- [0] 버그 수정
- [0] CSS 등 사용자 UI 디자인 변경
- [] 코드 리팩토링
- [] 문서 수정
link 수정 및 li 컬러 & 재배치
resolves #65
=> fix:index_nav_li link and depoly

src/components/category-contnet-page/category-contnet-page.css, src/components/main-card/main-card.css
- [] 새로운 기능 추가
- [] 문서 수정
1920px을 넘어가면 중앙정렬이 깨지는 오류를 수정했습니다
resolves #67
=> 🐛 fix:  반응형에 따른 카드 콘텐츠 너비 수정

src/pages/findId-page/findId-page.css, src/pages/findPw-page/findPw-page.css, src/pages/login-page/login-page.css, src/pages/signup-page/signup-page.css
- [] 새로운 기능 추가
- [0] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #68
=> 🐛fix:login~signup page max-width

src/components/category-contnet-page/category-contnet-page.css, src/components/footer/footer.css, src/components/main-card/main-card.css, src/components/main-visual/main-visual.css
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
1960px을 넘어가면 카드의 크기가 너무 커지는 오류 수정과 전체 너비를 수정 / footer 의 최대 너비 고정
resolves #70
=> 🐛 fix: 1960px을 넘어가면 카드의 크기가 너무 커지는 오류 수정과 전체 너비를 수정 / footer 의 최대 너비 고정

README.md
=> 📝 docs: readme 배포주소추가

package.json, src/components/footer/footer.css
footer가 작게 나오는 버그를 수정했습니다 --host는 ip유출 우려가있어서 삭제처리 했습니다
resolves #82
=> 🐛 fix:  footer width / 🔥 remove : --host

src/pages/findId-page/findId-page.html, src/pages/findPw-page/findPw-page.html, src/pages/login-page/login-page.html, src/pages/signup-page/signup-page.html
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
method=get으로 변경
resolves #
=> fix:method=get

src/components/clone-modal/clone-modal.html, src/components/main-card/main-card.css, src/components/main-card/main-card.html, src/components/main-nav/main-nav.html, src/components/main-visual/main-visual.html, src/pages/drama-page/drama-page.html, src/pages/findId-page/findId-page.html, src/pages/findPw-page/findPw-page.html, src/pages/landing-page/landing-page.html, src/pages/login-page/login-page.html, src/pages/main-page/main-page.html, src/pages/movie-page/movie-page.html, src/pages/profile-edit-page/profile-edit-page.html, src/pages/profile-edit-sub-page/profile-edit-sub-page.html, src/pages/profile-page/profile-page.html, src/pages/program-detail/program-detail.html, src/pages/signup-page/signup-page.html
접근성과 유효성 검사에서 인지된 오류를 최대한 수정해보았습니다
resolves #96
=> QA MAIN , DRAMA , MOVIE FOOTER

index.html, src/pages/findId-page/findId-page.css, src/pages/findId-page/findId-page.html, src/pages/findPw-page/findPw-page.css, src/pages/findPw-page/findPw-page.html, src/pages/login-page/login-page.html, src/pages/signup-page/signup-page.html, src/styles/index.css
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
index랑 login항목 페이지 전부 유효성검사 오류, 경고 fix
resolves #
=> 🐛fix:index and login's validation

intro.html, src/pages/mobile-search/mobile-search.html, src/pages/my-history/my-history.html, src/pages/program-detail/program-detail.html
=> 🐛 fix: 유효성검사 error 수정

index.html, src/pages/findId-page/findId-page.html, src/pages/findPw-page/findPw-page.html, src/pages/login-page/login-page.html, src/pages/signup-page/signup-page.html
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
head에서 link tag에 as="style" 제거 (index,login,findId,findPw,signup pages)
resolves #
=> fix: index and login's head link as fixed

src/pages/drama-page/drama-page.html, src/pages/main-page/main-page.html, src/pages/movie-page/movie-page.html
=> 🐛 fix: gnb헤더 부분 수정

src/components/main-card/main-card.html, src/components/main-nav/main-nav.html, src/pages/program-detail/program-detail.html
빌드시 오류나는 부분을 수정했습니다
resolves #101
=> 🐛 fix:  빌드 오류 수정

src/components/main-visual/main-visual.html, src/pages/login-page/login-page.html
=> 🐛 fix: map-error

index.html, src/pages/findId-page/findId-page.html, src/pages/signup-page/signup-page.html
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
인덱스 타이틀,아이콘 변경 및 아이디 찾기 회원가입 에러 수정
resolves #
=> 🐛fix: index title and findId, signup error

src/pages/program-detail/program-detail.html
=> 🐛 fix: 푸터 alt속성 두개 수정

src/pages/profile-edit-sub-page/profile-edit-sub-page.html
=> 🐛 fix : 빌드 오류 수정
